### ISSUE TITLE
Week 5 Announcement Brain Dump

### ISSUE THREAD

**Issue by ginge270** [thoth-tech/handbook#34]
Congrats on the excellent feedback about Task 2.1
Starting to think about your retrospective (6.1) / task 5.1
Watch the D/HD workshop video (benefitial for everyone)
Fill in the learning survey
Seniors who want to mentor – reach out
Juniors who would like to work towards leadership next trimester (EOI for attending the leadership conference being organised)
Showcase for D/HD students being organised at the end of the week - presenting to MDs with trello board, plans, testing & data strategies (fill in the templates) - great place for feedback
By now trello boards should planned out, upskilling should already be happening
Comfortable in github, creating pull requests
Review the QA doc – there will be a session on this during the week
Transition away from word docs – everything moving towards thoth tech from this week onward.
Ensure you have cloned your repos from the Thoth Tech organisation - not doubtfirelms

**Comment by kats8** [comment]
Any students who didn't get 1.1P the first time around, note the task sheet has been regenerated to make it clearer, and today's (Monday 4 April) lecture shows how to find the CLO's for your course.

If you wish to have feedback on 5.1 please submit your draft to a lead (Liz and/or others?) by Friday

While there is a focus on students having responsibility for sourcing their work in capstone, if a student finds themselves with nothing to do and is unsure , they should, at a minimum, speak to their team leader to ask "what can I do?". A reminder: even if you are only looking for a pass grade, it is up to you to make sure you have work to demonstrate requirements.

**Comment by ghost** [comment]
Mentioning the new communication guidelines and practices now in Handbook

**Comment by tancnle** [comment]
Leads to organise time for presentation and preparing the materials.

**Comment by tancnle** [comment]
Remind team to start looking at the Software Requirements Specification in preparation for task 6.2
