### ISSUE TITLE
Week 6 Announcement Brain Dump

### ISSUE THREAD

**Issue by ghost** [thoth-tech/handbook#61]
Focus is on development?
Task 6.x this week
Documentation now going into the documentation repo (https://github.com/thoth-tech/documentation)
- If the file is relevant companywide and for more than one trimester, it goes in the handbook repo
- If the file is relevant to a product or project, it goes in the documentation repo

Start thinking about off-boarding and trimester transition

**Comment by ginge270** [comment]
Company report task due at end of  trimester break - instructions and due date to come later this week
Post about  all company meeting date
Question forum
6.1 & 6.2 due soon
Reminder if you are aiming for d/HD 4 task due on the same day
Area leads will be popping into your meetings this week - if your meeting is not in the company calendar or the time changes - please put it in there/communicate with us

By now you should have:
- received project epics
- broken it down into user stories
- trello boards filled out in depth with clear communication on what is happening
- software requirements 
- discussed data requirements
- dicussed testing requrements
- have documented your work and progress
- had your first retro
- feel confident in what you are doing - if you do not - REACH OUT
- upskilled
- ...

Now:
Leadership conference sign ups
Data and Testing strategy templates filled out this week ready to present in company report

**Comment by ginge270** [comment]
6.2 team progress updates will be worked on as a company in a PR in github and then submitted as an .md document to the Thoth Tech Handbook repo folder xxxx by  (suggest 21st considering the number of tasks due on the same day) date as per the task sheet. Branch to contribute to for this task is task6.2/company-report-project-updates (https://github.com/thoth-tech/handbook/pull/63)
