### ISSUE TITLE
Project meeting schedule assignment for this week

### ISSUE THREAD

**Issue by ginge270** [thoth-tech/handbook#64]
Tuesday:

3pm: Dreambig Prototype 1 
4:30pm: SK Extensions meeting
4:45pm: SK  Operations meeting

Wednesday:

7pm: Documentation meeting

Thursday:

1pm: OT Voice Verification
5pm: Dreambig Prototype Meeting 2

Unsure:

Front-end migration
Deployment
Internal Systems 
Applications (sundays?)
Modules
Jupyter notebook

**Comment by ghost** [comment]
Deployment Thursday at 4pm

**Comment by tancnle** [comment]
Modules - 6:00-6:30 pm Thursday
Internal Systems - 5:30-6:00 pm Saturday
Applications - 3:00-3:30 pm Sunday
Front-end migration - 6:30-7:00 pm Tuesday

**Comment by ghost** [comment]
4:30pm: SK Extensions meeting
4:45pm: SK Operations meeting
These are showcases to Glory - not standups
