### ISSUE TITLE
Week 8 Brain Dump

### ISSUE THREAD

**Issue by kats8** [thoth-tech/handbook#82]
T2 2022 questionnaire: JUNIORS please fill this out to assist with ensuring you are placed appropriately next year and get a chance to take on roles and growth opportunities of interest. This is your chance to have your say.

Test strategy: has your team completed yours? This is an important part of the Quality Assurance process and should exist before you start coding. Reminder, a sample [Test Strategy template](https://github.com/thoth-tech/handbook/blob/main/docs/processes/quality-assurance/templates/test-strategy-template.md) is in the handbook. If you have particular testing resources and skills, there will be opportunities to express interest this week to help out your fellow Thoth-Tech company members.

Remember to book into your calendars, next Monday 9th of May, Daniel from Midnyte City is presenting an guest session all around [Experience working in Industry](https://teams.microsoft.com/l/meetup-join/19%3ameeting_OGJiNDMwMjMtNTY5Ni00NmE3LWJhNzgtNDdiODVkMjQ3ZTMy%40thread.v2/0?context=%7b%22Tid%22%3a%22d02378ec-1688-46d5-8540-1c28b5f470f6%22%2c%22Oid%22%3a%2228d124d9-c7f9-4243-a99d-1d4345d9f65c%22%7d). It’s at 12-1pm so you can dial in over lunchtime. Daniel has real world delivery lead experience, so this is a great opportunity to gain valuable insight into the real world and enhance your capstone leadership learnings.

**Comment by ghost** [comment]
As you are all aware there is a ~new~ documentation repo. Please begin putting your research and development notes into the corresponding folder. This is expected to be completed in time for handover (Week 11). If you start now you will have no issues. Remember to add people from your project and docs team to review the Pull Request.

**Comment by tancnle** [comment]
We would love some input regarding your project key results and the data required to validate that. Please see the [Project metrics template](https://github.com/thoth-tech/handbook/blob/main/docs/data/project-metrics-template.md) for some guidance. **The key results are not only restricted to the product**. They can encompass delivery and people. For example, successfully upskill 100% of team members on TypeScript, etc.

**Comment by ghost** [comment]
Thank you to the 31 responses in the Onboarding feedback form. This will be invaluable information for next trimester. We are happy to report a 4/5 stars for on-boarding, hopefully next tri will reach 5/5.
