### ISSUE TITLE
Leadership Recommendations for T2

### ISSUE THREAD

**Issue by ginge270** [thoth-tech/handbook#89]
Onboarding form improvements:
- skill confidence (1-5) eg. programming, troubleshooting, documentation, project collaboration etc
- do you want to work towards leadership?

- Product Lead + Area lead merged
- Addition of more area leads
- QA team
- Documentation team part of Internal Systems
- Delivery lead training in week 0
- Implement recommendations from T1 Delivery leads

**Comment by ghost** [comment]
do you want to push soft skills or progress?
